USE PANEL;

CALL CAD_PASS_CLIENT('ABCDEFGHIJ', 'Pediatra', 'GUICHE001');
CALL CAD_PASS_CLIENT('BCDEFGHIJK', 'Oftalmologista', 'GUICHE002');  
CALL CAD_PASS_CLIENT('CDEFGHIJKL', 'Cardiologista', 'GUICHE003');
CALL CAD_PASS_CLIENT('DEFGHIJKLM', 'Ortopedista', 'GUICHE004');
CALL CAD_PASS_CLIENT('EFGHIJKLMN', 'Ginecologista', 'GUICHE005');
CALL CAD_PASS_CLIENT('FGHIJKLMNO', 'Otorrinolaringologista', 'GUICHE002');
CALL CAD_PASS_CLIENT('GHIJKLMNOP', 'Pediatra', 'GUICHE002');
CALL CAD_PASS_CLIENT('HIJKLMNOPQ', 'Oftalmologista', 'GUICHE005');
CALL CAD_PASS_CLIENT('IJKLMNOPQR', 'Cardiologista', 'GUICHE004');  
CALL CAD_PASS_CLIENT('JKLMNOPQRS', 'Ortopedista', 'GUICHE003');
CALL CAD_PASS_CLIENT('KLMNOPQRST', 'Ginecologista', 'GUICHE002');
CALL CAD_PASS_CLIENT('LMNOPQRSTU', 'Otorrinolaringologista', 'GUICHE001');
CALL CAD_PASS_CLIENT('MNOPQRSTUV', 'Pediatra', 'GUICHE005');
CALL CAD_PASS_CLIENT('NOPQRSTUVW', 'Oftalmologista', 'GUICHE004');
CALL CAD_PASS_CLIENT('OPQRSTUVWX', 'Cardiologista', 'GUICHE002');
CALL CAD_PASS_CLIENT('PQRSTUVWXY', 'Ortopedista', 'GUICHE004'); 
CALL CAD_PASS_CLIENT('QRSTUVWXY', 'Ginecologista', 'GUICHE005');
CALL CAD_PASS_CLIENT('RSTUVWXYZA', 'Otorrinolaringologista', 'GUICHE001');
CALL CAD_PASS_CLIENT('RSTUVWXYeA', 'Otorrinolaringologista', 'GUICHE005');

SELECT * FROM PANEL_PASS;
